echo "5"
echo "4"
echo "3"
echo "2"
echo "1"
echo "MAPES IS ALIVE!"
echo "Lets light this world on FIRE!"
echo "Its the rise of M.A.P.E.S.AI"
echo "By: Richard Shover & Nexus Gamez"
streamlit run mapes.py
